---
- name: Print ec2 information
  debug: var=hostvars['n2n2-node'].ec2

# - name: Print all available facts
#   ansible.builtin.debug:
#     var: ansible_facts

- name: Set NODE_DOMAIN
  lineinfile:
    dest: /etc/environment
    create: yes
    state: present
    regexp: "^NODE_DOMAIN"
    line: "NODE_DOMAIN={{ hostvars['n2n2-node'].ec2.tagged_instances[0].tags['Name'] }}.n2n2.chat"
  become: yes

- name: Mkdir n2n2 client path dir
  file:
    path: "{{ n2n2_path }}"
    state: directory
    owner: ubuntu
  become: true
  tags: provisioning

- name: add github ssh key
  copy: >
    src=~/.ssh/id_rsa.github
    dest=/root/.ssh/id_rsa.github
    owner=root
    group=root
    mode=0600
  become: yes

- name: add github ssh key
  copy: >
    src=~/.ssh/id_rsa.github.pub
    dest=/root/.ssh/id_rsa.github.pub
    owner=root
    group=root
    mode=0600
  become: yes

- name: configure ssh to use ansible key for github.com
  template: >
    src=templates/ssh_config.j2
    dest=/root/.ssh/config
    owner=root
    group=root
    mode=0644
  become: yes

- name: Add and load private key to ssh-agent
  shell: "eval `ssh-agent -s` && ssh-add /root/.ssh/id_rsa.github"
  become: yes

- name: Set authorized key took from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.github.pub') }}"
  become: yes

- name: clone a private repository
  git: >
    repo=git@github.com:n2n2dev/n2n2-relay.git
    key_file=/root/.ssh/id_rsa.github
    dest={{ n2n2_path }}
    version={{ git_branch }}
    force=yes
    update=yes
  become: yes

- name: Fix permissions
  file:
    path: /srv
    owner: ubuntu
    group: ubuntu
    mode: 0755
    state: directory
    recurse: yes
  become: yes
